### ISSUE TITLE
module Utils

### ISSUE THREAD

**Issue by vinc42** [CPUlm/CSimulator#5]
https://github.com/CPUlm/SimulateurC/blob/72fa0bb9dd893851c9c31b3d21c40384643545e5/bin/csimulator.ml#L31C13-L31C28

La doc ocaml n'a pas l'air de connaitre ce module (et mon compilateur non plus)

**Comment by desfreng** [comment]
C'est parce-qu'il n'existe pas ! J'avais complètement terminé de passer sur Dune, et j'ai oublié de retirer les dernières références à `Utils`.

Un _fix_ tout simple : Retirer tous les `Utils.` du code. La PR de @hgruniaux (#3) devrait fixer également ce problème !

**Comment by hgruniaux** [comment]
Corrigé dans #3
